# ===============================
# CONFIGURACION DEL SERVIDOR
# ===============================
server.port=8081
spring.application.name=servicio-pedidos

# ===============================
# CONFIGURACION DE POSTGRESQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACION DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACION DE JWT
# ===============================
jwt.secret=${JWT_SECRET_KEY}

# ==================================
# CONFIGURACION DE MICROMETER TRACING
# ==================================
# Como es un servidor de prueba, aniaado al 100% de las cabeceras el Trace
# En produccion esto supondria una gran saturacion.
management.tracing.sampling.probability=1.0
management.tracing.enabled=true

logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management.zipkin.tracing.export.enabled=false
logging.level.com.portfolio=INFO